#!/bin/sh

case $# in
0)	echo "Usage: $0 N" 1>&2
	echo "  Produces N by N tilted lattice" 1>&2
	exit 1
	;;
esac

n=$1

i=1
while [ $i -le $n ]
do
    j=1
    while [ $j -le $n ]
    do
	x=`expr 2 \* $i - 2`
	y=`expr 2 \* $j - 2`
	echo "$x $y"
	j=`expr $j + 1`
    done
    if [ $i -lt $n ]
    then
	j=1
	while [ $j -lt $n ]
	do
	    x=`expr 2 \* $i - 1`
	    y=`expr 2 \* $j - 1`
	    echo "$x $y"
	    j=`expr $j + 1`
	done
    fi
    i=`expr $i + 1`
done
